#index:
#    path: /
#    controller: App\Controller\DefaultController::index

operacion_cheques_portador:
    path: /operacion/ChequePortador/{id}
    controller: App\Controller\OperacionController::listChequePortador
    methods: [GET]

operacion_pts_sesion:
    path: /puntaje
    controller: App\Controller\OperacionController::darPuntaje
    methods: [POST]

usuario:
    path: /usuario/{email}
    controller: App\Controller\UsuarioController::index

usuario_editar:
    path: /usuario/editar/{email}
    controller: App\Controller\UsuarioController::editar


home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /
    controller: App\Controller\SecurityController::login

logout:
    path: /logout