#index:
#    path: /
#    controller: App\Controller\DefaultController::index

operacion_cheques_portador:
    path: /operacion/ChequePortador/{id}
    controller: App\Controller\OperacionController::listChequePortador
    methods: [GET]

operacion_pts_sesion:
    path: /puntaje
    controller: App\Controller\OperacionController::darPuntaje
    methods: [POST]

usuario:
    path: /usuario/{email}
    controller: App\Controller\UsuarioController::index

usuario_editar:
    path: /usuario/editar/{email}
    controller: App\Controller\UsuarioController::editar

cheques:
    path: /cheques
    controller: App\Controller\ChequeController::index

cedulas:
    path: /cedulas
    controller: App\Controller\CedulaController::index

bancos:
    path: /bancos
    controller: App\Controller\BancoController::index

empresas:
    path: /empresas
    controller: App\Controller\EmpresaController::index

alumnos_empresa:
    path: /alumnos_empresa
    controller: App\Controller\AlumnoController::obtenerAlumnosEmpresa
    methods: [POST]

alumnos:
    path: /alumnos
    controller: App\Controller\AlumnoController::index

home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /
    controller: App\Controller\SecurityController::login

logout:
    path: /logout