#index:
#    path: /
#    controller: App\Controller\DefaultController::index

operacion_pts_sesion:
    path: /puntaje
    controller: App\Controller\OperacionController::darPuntaje
    methods: [POST]