#index:
#    path: /
#    controller: App\Controller\DefaultController::index

operacion_cheques_portador:
    path: /operacion/ChequePortador/{id}
    controller: App\Controller\OperacionController::listChequePortador
    methods: [GET]

operacion_pts_sesion:
    path: /puntaje
    controller: App\Controller\OperacionController::darPuntaje
    methods: [POST]

usuario:
    path: /usuario/{email}
    controller: App\Controller\UsuarioController::index

usuario_editar:
    path: /usuario/editar/{email}
    controller: App\Controller\UsuarioController::editar

#CHEQUES-------------------------
cheques:
    path: /cheques
    controller: App\Controller\ChequeController::index

cheque_nuevo:
    path: /cheque/nuevo
    controller: App\Controller\ChequeController::new

cheque_mostrar:
    path: /cheque/detalle/{id}
    controller: App\Controller\ChequeController::show

cheque_editar:
    path: /cheque/editar/{id}
    controller: App\Controller\ChequeController::edit

cheque_eliminar:
    path: /cheque/eliminar/{id}
    controller: App\Controller\ChequeController::delete

#CEDULAS-------------------------
cedulas:
    path: /cedulas
    controller: App\Controller\CedulaController::index

cedula_nuevo:
    path: /cedula/nuevo
    controller: App\Controller\CedulaController::new

cedula_mostrar:
    path: /cedula/detalle/{id}
    controller: App\Controller\CedulaController::show

cedula_editar:
    path: /cedula/editar/{id}
    controller: App\Controller\CedulaController::edit

cedula_eliminar:
    path: /cedula/eliminar/{id}
    controller: App\Controller\CedulaController::delete

#BANCOS-------------------------
bancos:
    path: /bancos
    controller: App\Controller\BancoController::index

banco_nuevo:
    path: /banco/nuevo
    controller: App\Controller\BancoController::new

banco_mostrar:
    path: /banco/detalle/{id}
    controller: App\Controller\BancoController::show

banco_editar:
    path: /banco/editar/{id}
    controller: App\Controller\BancoController::edit

banco_eliminar:
    path: /banco/eliminar/{id}
    controller: App\Controller\BancoController::delete


#EMPRESAS-------------------------
empresas:
    path: /empresas
    controller: App\Controller\EmpresaController::index

empresa_nuevo:
    path: /empresa/nuevo
    controller: App\Controller\EmpresaController::new

empresa_mostrar:
    path: /empresa/detalle/{id}
    controller: App\Controller\EmpresaController::show

empresa_editar:
    path: /empresa/editar/{id}
    controller: App\Controller\EmpresaController::edit

empresa_eliminar:
    path: /empresa/eliminar/{id}
    controller: App\Controller\EmpresaController::delete

alumnos_empresa:
    path: /alumnos_empresa
    controller: App\Controller\AlumnoController::obtenerAlumnosEmpresa
    methods: [POST]

#ALUMNOS-------------------------
alumnos:
    path: /alumnos
    controller: App\Controller\AlumnoController::index

alumno_nuevo:
    path: /alumno/nuevo
    controller: App\Controller\AlumnoController::new

alumno_mostrar:
    path: /alumno/detalle/{id}
    controller: App\Controller\AlumnoController::show

alumno_editar:
    path: /alumno/editar/{id}
    controller: App\Controller\AlumnoController::edit

alumno_eliminar:
    path: /alumno/eliminar/{id}
    controller: App\Controller\AlumnoController::delete

home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

   
